export const tasks = [
  {
    id: "task-1",
    title: "Task 1",
    description: "Description 1",
    priority: "High",
    dueDate: "2022-12-31",
    status: "Pending",
    columnId: "column-1",
  },
  {
    id: "task-2",
    title: "Task 2",
    description: "Description 2",
    priority: "Medium",
    dueDate: "2023-01-05",
    status: "In Progress",
    columnId: "column-1",
  },
  {
    id: "task-3",
    title: "Task 3",
    description: "Description 3",
    priority: "Low",
    dueDate: "2022-12-28",
    status: "Completed",
    columnId: "column-1",
  },
  {
    id: "task-4",
    title: "Task 4",
    description: "Description 4",
    priority: "Low",
    dueDate: "2022-12-28",
    status: "Backlog",
    columnId: "column-1",
  },
  {
    id: "task-5",
    title: "Task 5",
    description: "Description 5",
    priority: "Medium",
    dueDate: "2022-12-28",
    status: "In Progress",
    columnId: "column-1",
  },
  {
    id: "task-6",
    title: "Task 6",
    description: "Description 6",
    priority: "High",
    dueDate: "2022-12-28",
    status: "Completed",
    columnId: "column-1",
  },
];
